[debug] [2020-04-01T15:08:09.478Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:08:09.482Z] Command:       C:\Users\johns\scoop\apps\nodejs\current\node.exe C:\Users\johns\scoop\apps\nodejs\current\bin\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-01T15:08:09.482Z] CLI Version:   8.0.0
[debug] [2020-04-01T15:08:09.482Z] Platform:      win32
[debug] [2020-04-01T15:08:09.483Z] Node Version:  v13.1.0
[debug] [2020-04-01T15:08:09.485Z] Time:          Wed Apr 01 2020 10:08:09 GMT-0500 (Central Daylight Time)
[debug] [2020-04-01T15:08:09.485Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:08:09.485Z] 
[debug] [2020-04-01T15:08:09.502Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-01T15:08:10.166Z] Error: Unexpected error determining execution environment: Invalid response from metadata service: incorrect Metadata-Flavor header.
    at metadataAccessor (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:60:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.isAvailable (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:161:9)
    at async GoogleAuth._checkIsGCE (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:176:31)
    at async GoogleAuth.getApplicationDefaultAsync (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:152:21)
    at async GoogleAuth.getClient (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-01T15:08:35.225Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:08:35.229Z] Command:       C:\Users\johns\scoop\apps\nodejs\current\node.exe C:\Users\johns\scoop\apps\nodejs\current\bin\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-01T15:08:35.229Z] CLI Version:   8.0.0
[debug] [2020-04-01T15:08:35.229Z] Platform:      win32
[debug] [2020-04-01T15:08:35.229Z] Node Version:  v13.1.0
[debug] [2020-04-01T15:08:35.231Z] Time:          Wed Apr 01 2020 10:08:35 GMT-0500 (Central Daylight Time)
[debug] [2020-04-01T15:08:35.232Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:08:35.232Z] 
[debug] [2020-04-01T15:08:35.243Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-01T15:08:36.186Z] Error: Unexpected error determining execution environment: Invalid response from metadata service: incorrect Metadata-Flavor header.
    at metadataAccessor (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:60:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.isAvailable (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:161:9)
    at async GoogleAuth._checkIsGCE (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:176:31)
    at async GoogleAuth.getApplicationDefaultAsync (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:152:21)
    at async GoogleAuth.getClient (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-01T15:09:49.966Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:09:49.969Z] Command:       C:\Users\johns\scoop\apps\nodejs\current\node.exe C:\Users\johns\scoop\apps\nodejs\current\bin\node_modules\firebase-tools\lib\bin\firebase.js init --debug
[debug] [2020-04-01T15:09:49.970Z] CLI Version:   8.0.0
[debug] [2020-04-01T15:09:49.970Z] Platform:      win32
[debug] [2020-04-01T15:09:49.970Z] Node Version:  v13.1.0
[debug] [2020-04-01T15:09:49.971Z] Time:          Wed Apr 01 2020 10:09:49 GMT-0500 (Central Daylight Time)
[debug] [2020-04-01T15:09:49.972Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:09:49.972Z] 
[debug] [2020-04-01T15:09:49.982Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-01T15:09:50.838Z] Error: Unexpected error determining execution environment: Invalid response from metadata service: incorrect Metadata-Flavor header.
    at metadataAccessor (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:60:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.isAvailable (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:161:9)
    at async GoogleAuth._checkIsGCE (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:176:31)
    at async GoogleAuth.getApplicationDefaultAsync (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:152:21)
    at async GoogleAuth.getClient (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-01T15:13:20.466Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:13:20.470Z] Command:       C:\Users\johns\scoop\apps\nodejs\current\node.exe C:\Users\johns\scoop\apps\nodejs\current\bin\node_modules\firebase-tools\lib\bin\firebase.js init --debug
[debug] [2020-04-01T15:13:20.471Z] CLI Version:   8.0.0
[debug] [2020-04-01T15:13:20.471Z] Platform:      win32
[debug] [2020-04-01T15:13:20.471Z] Node Version:  v13.1.0
[debug] [2020-04-01T15:13:20.485Z] Time:          Wed Apr 01 2020 10:13:20 GMT-0500 (Central Daylight Time)
[debug] [2020-04-01T15:13:20.485Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:13:20.485Z] 
[debug] [2020-04-01T15:13:20.523Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-01T15:13:20.849Z] Error: Unexpected error determining execution environment: Invalid response from metadata service: incorrect Metadata-Flavor header.
    at metadataAccessor (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:60:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.isAvailable (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:161:9)
    at async GoogleAuth._checkIsGCE (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:176:31)
    at async GoogleAuth.getApplicationDefaultAsync (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:152:21)
    at async GoogleAuth.getClient (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-01T15:48:34.608Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:48:34.612Z] Command:       C:\Users\johns\scoop\apps\nodejs\current\node.exe C:\Users\johns\scoop\apps\nodejs\current\bin\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-01T15:48:34.613Z] CLI Version:   8.0.0
[debug] [2020-04-01T15:48:34.613Z] Platform:      win32
[debug] [2020-04-01T15:48:34.614Z] Node Version:  v13.1.0
[debug] [2020-04-01T15:48:34.627Z] Time:          Wed Apr 01 2020 10:48:34 GMT-0500 (Central Daylight Time)
[debug] [2020-04-01T15:48:34.628Z] ----------------------------------------------------------------------
[debug] [2020-04-01T15:48:34.628Z] 
[debug] [2020-04-01T15:48:34.669Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-01T15:48:36.810Z] Error: Unexpected error determining execution environment: Invalid response from metadata service: incorrect Metadata-Flavor header.
    at metadataAccessor (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:60:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.isAvailable (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\gcp-metadata\build\src\index.js:161:9)
    at async GoogleAuth._checkIsGCE (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:176:31)
    at async GoogleAuth.getApplicationDefaultAsync (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:152:21)
    at async GoogleAuth.getClient (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\johns\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
